apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dns-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-controller
    spec:
      containers:
      - name: dns-controller
        image: nicksuckling/dns-controller-arm:1.8.0-beta.2
        imagePullPolicy: Always
        volumeMounts:
        - name: aws-credentials
          mountPath: /root/.aws/
          readOnly: true
      volumes:
      - name: aws-credentials
        secret:
          secretName: aws-creds-route53
