apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring
  labels:
    k8s-app: monitoring
spec:
  capacity:
    storage: 4G
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.0.27"
    path: "/volume1/kube"

